[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "rust"
path = "src/main.rs"

[[bin]]
name = "rust2"
path = "src/main2.rs"

[[bin]]
name = "rust3"
path = "src/structs.rs"

